// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: currencies.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCurrencies = `-- name: CreateCurrencies :one
INSERT INTO currencies (id, name, code, price, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, code, price, created_at, updated_at
`

type CreateCurrenciesParams struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Price     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCurrencies(ctx context.Context, arg CreateCurrenciesParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, createCurrencies,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Price,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrencies = `-- name: GetCurrencies :many
SELECT id, name, code, price, created_at, updated_at FROM currencies
`

func (q *Queries) GetCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, getCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT id, name, code, price, created_at, updated_at FROM currencies
WHERE code = $1
`

func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, code)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCurrencyPrice = `-- name: UpdateCurrencyPrice :many
UPDATE currencies
SET price = $2
WHERE id = $1
RETURNING id, name, code, price, created_at, updated_at
`

type UpdateCurrencyPriceParams struct {
	ID    uuid.UUID
	Price string
}

func (q *Queries) UpdateCurrencyPrice(ctx context.Context, arg UpdateCurrencyPriceParams) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, updateCurrencyPrice, arg.ID, arg.Price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
