// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID         uuid.UUID
	CurrencyID uuid.UUID
	UserID     uuid.UUID
	Amount     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Currency struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Price     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	ApiKey    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
